import type Engineer from '../types/engineer.types';

export const ENGINEERS: Engineer[] = [
  {
    id: 1,
    name: 'Gennadiy Greiner',
    email: 'genagreiner94@gmail.com',
    linkedin: 'https://linkedin.com',
    photoUrl: './teamMembers/gennadiyPhoto.png',
    github: 'https://github.com/greiner94',
  },
  {
    id: 2,
    name: 'Pavlo Kataranchuk',
    email: 'pavel83838300@gmail.com',
    linkedin: 'https://www.linkedin.com/in/pavlo-kataranchuk-tech-partner/',
    photoUrl: './teamMembers/pavloPhoto.jpg',
    github: 'https://github.com/PavloJedi',
  },
  {
    id: 3,
    name: 'Vladyslav Kononenko',
    email: 'kononvlad007@gmail.com',
    linkedin: 'https://www.linkedin.com/in/vladyslav-kon/',
    photoUrl: './teamMembers/vladyslavPhoto.png',
    github: 'https://github.com/premiumderyn',
  },
  {
    id: 4,
    name: 'Mykola Korostelov',
    email: 'nkorostelev59@gmail.com',
    linkedin: 'https://www.linkedin.com/in/korostelovm/',
    photoUrl: './teamMembers/mykolaPhoto.jpg',
    github: 'https://github.com/Fronik123',
  },
  {
    id: 5,
    name: 'Viktor Kushchevoi',
    email: 'victork1609@gmail.com',
    linkedin: 'https://www.linkedin.com/in/viktor-kushchevoi-a35226284/',
    photoUrl: './teamMembers/viktorPhoto.jpg',
    github: 'https://github.com/ViktorKushchevoi',
  },
  {
    id: 6,
    name: 'Anastasiia Moroz',
    email: 'anastasiamoroz.dev@gmail.com',
    linkedin: 'https://www.linkedin.com/in/anastasiia-moroz-2g5n7g/',
    photoUrl: './teamMembers/anastasiiaPhoto.jpg',
    github: 'https://github.com/yunaree',
  },
  {
    id: 7,
    name: 'Oleksii Poletaev',
    email: 'poletaev.alexei@gmail.com',
    linkedin: 'https://linkedin.com',
    photoUrl: './teamMembers/oleksiiPhoto.jpg',
    github: 'https://github.com/apoletaev',
  },
  {
    id: 8,
    name: 'Anastasiia Tkachenko',
    email: 'kixippi.work@gmail.com',
    linkedin: 'https://www.linkedin.com/in/anastasiia-tkachenko-2021343b3',
    photoUrl: './teamMembers/anastasiiaTkPhoto.jpg',
    github: 'https://github.com/nnnnastia',
  },
  {
    id: 9,
    name: 'Olha Khomych',
    email: 'o.fedorchuk1@gmail.com',
    linkedin: 'https://linkedin.com',
    photoUrl: './teamMembers/olhaPhoto.jpg',
    github: 'https://github.com/ofedorchuk1',
  },
  {
    id: 10,
    name: 'Kateryna Chukhrai',
    email: 'kachukhrai@gmail.com',
    linkedin: 'https://www.linkedin.com/in/kateryna-chukhrai/',
    photoUrl: './teamMembers/katerynaPhoto.jpg',
    github: 'https://github.com/churight',
  },
  {
    id: 11,
    name: 'Diana Shymanska',
    email: 'shymanskadianaa@gmail.com',
    linkedin: 'https://www.linkedin.com/in/diana-shymanska-aa262a2b8',
    photoUrl: './teamMembers/dianaPhoto.jpg',
    github: 'https://github.com/dianajnxv',
  },
];
